export const CREATE_COURSE="CREATE_COURSE"
export const CREATE_COURSE_SUCCESS="CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAILURE="CREATE_COURSE_FAILURE"
export const FETCH_COURSE="FETCH_COURSE";
export const FETCH_COURSE_SUCCESS="FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILURE="FETCH_COURSE_FAILURE";
export const DELETE_COURSE="DELETE_COURSE";